### ISSUE TITLE
Cannot get this to function

### ISSUE THREAD

**Issue by jackkeller** [morassman/tabasco#4]
Is there any dependancies needed? I grab a tab, pull it around and never get a highlighted region to drop it and create a new pane.

**Comment by morassman** [comment]
This might be due to a bug. I wasn't able to reproduce the issue, but from the code I could see a way for this to happen.

Tabasco relies on the tabs to have already been added to a pane by the time the workspace notifies it of the pane. Although, if the tabs package activates _after_ tabasco does, then it might cause tabasco to be notified of a pane before the tabs are actually added.

Even though support was added to ensure tabasco works regardless of activation order, support wasn't added for pane notification order.

I added support for this in v0.4.0. Since I couldn't reproduce the issue I can't be 100% sure that it fixes the problem. Please update to v0.4.0 and test again.

If it still doesn't work then just restart Atom and see if it helps. One thing that I have found is that a package's styles do not always take immediate effect after installing or updating and the only way one can see tabasco's drop zones is if the styles can be applied.

**Comment by infogulch** [comment]
I'm also encountering this bug, but only when I enable the [atom-material-ui](https://atom.io/themes/atom-material-ui) theme.

**Comment by morassman** [comment]
The atom-material-ui theme seems to add a z-index to the pane that caused tabasco's drop zones to end up behind it. v0.4.1 takes care of it. I've tested and it works with atom-material-ui, but there might be other packages/themes that has similar side effects.

**Comment by infogulch** [comment]
Thanks!

Yes, unfortunately there are a lot of things that could have side-effects that break it.

**Comment by morassman** [comment]
Yeah. That's the downside of a very pluggable environment I guess, but I'll cross those bridges when I get there :)
