### ISSUE TITLE
Cannot drag tab from inactive pane

### ISSUE THREAD

**Issue by infogulch** [morassman/tabasco#6]
1. Create two panes with two tabs in each.
2. Activate a tab in the first pane.
3. _Without touching anything else_, click-drag a tab from the second pane in a single click.
4. The tab does not drag or show the docking graphics. It should.

From the [gif graphic](https://github.com/morassman/tabasco/blob/master/resources/demo.gif?raw=true) in the README, your first 3 actions are below. I'm stating that you should be able to remove step 2 entirely and it should still work.
1. Drag `package.json` to a new pane.
2. Click to select `tab-grab.coffee`
3. Click-Drag `tab-grab.coffee` to a new pane.

**Comment by morassman** [comment]
This behaviour is due to how the [tabs](https://atom.io/packages/tabs) package is implemented. Tabasco depends on the tabs package and only created the drop zones when it detects that a tab is being dragged. Even without tabasco installed one can only drag a tab from the pane that is currently active.

This is unfortunately out of my hands. If you'd like you can add a feature request to the tabs repo. If they add support for this by allowing the tabs from inactive tabs to be dragged and it generates the same drag event then tabasco should pick it up.

**Comment by infogulch** [comment]
I see. Thanks for the info. Yes, I will be opening an issue on the tabs package if it doesn't already exist.

Feel free to close if you want, otherwise I'll probably link the tabs issue I create to here for reference and update you here if anything interesting happens.

Thanks again!

**Comment by morassman** [comment]
I'll just close this one for now. If it gets implemented and tabasco doesn't work with it then I'll fix it, but if you come across it before I do then you're welcome to just log another issue.

Thanks for the feedback!
